export default {
  mainnet: {
    address: '',
    abi: [],
  },
  kovan: {
    FactoryErc721: {
      address: '0xDD51BCb7a7F39148B8ADfB08Cb1DAEaB2A4c71C4',
      abi: [
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          stateMutability: 'nonpayable',
          type: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'newToken',
              type: 'address',
            },
            { indexed: false, internalType: 'string', name: 'name', type: 'string' },
            {
              indexed: false,
              internalType: 'string',
              name: 'symbol',
              type: 'string',
            },
            { indexed: true, internalType: 'address', name: 'signer', type: 'address' },
          ],
          name: 'ERC721Made',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'exchange',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'string', name: 'name', type: 'string' },
            {
              internalType: 'string',
              name: 'symbol',
              type: 'string',
            },
            { internalType: 'string', name: 'baseURI', type: 'string' },
            {
              internalType: 'address',
              name: 'signer',
              type: 'address',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeERC721',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          name: 'setExchange',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
    FactoryErc1155: {
      address: '0x9847603DeA9F66cBB6B9f080B4B2D0a95c17FE7b',
      abi: [
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          stateMutability: 'nonpayable',
          type: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: false, internalType: 'address', name: 'newToken', type: 'address' },
            {
              indexed: true,
              internalType: 'address',
              name: 'signer',
              type: 'address',
            },
          ],
          name: 'ERC1155Made',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'exchange',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'string', name: 'uri', type: 'string' },
            {
              internalType: 'address',
              name: 'signer',
              type: 'address',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeERC1155',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          name: 'setExchange',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
    Exchange: {
      address: '0x405E1041ECAbb850931D868AB152255cF921D992',
      abi: [
        { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'seller',
              type: 'address',
            },
            { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
            {
              indexed: false,
              internalType: 'address',
              name: 'sellTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'sellId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'sellAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address',
              name: 'buyTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'buyId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'buyAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address[]',
              name: 'feeAddresses',
              type: 'address[]',
            },
            { indexed: false, internalType: 'uint256[]', name: 'feeAmounts', type: 'uint256[]' },
          ],
          name: 'ExchangeMadeErc1155',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'seller',
              type: 'address',
            },
            { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
            {
              indexed: false,
              internalType: 'address',
              name: 'sellTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'sellId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'sellAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address',
              name: 'buyTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'buyId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'buyAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address[]',
              name: 'feeAddresses',
              type: 'address[]',
            },
            { indexed: false, internalType: 'uint256[]', name: 'feeAmounts', type: 'uint256[]' },
          ],
          name: 'ExchangeMadeErc721',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'idOrder', type: 'bytes32' },
            {
              internalType: 'address[2]',
              name: 'SellerBuyer',
              type: 'address[2]',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToBuy',
              type: 'tuple',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToSell',
              type: 'tuple',
            },
            { internalType: 'address[]', name: 'feeAddresses', type: 'address[]' },
            {
              internalType: 'uint256[]',
              name: 'feeAmounts',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeExchangeERC1155',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'idOrder', type: 'bytes32' },
            {
              internalType: 'address[2]',
              name: 'SellerBuyer',
              type: 'address[2]',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToBuy',
              type: 'tuple',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToSell',
              type: 'tuple',
            },
            { internalType: 'address[]', name: 'feeAddresses', type: 'address[]' },
            {
              internalType: 'uint256[]',
              name: 'feeAmounts',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeExchangeERC721',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256[]', name: '', type: 'uint256[]' },
            {
              internalType: 'uint256[]',
              name: '',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: '', type: 'bytes' },
          ],
          name: 'onERC1155BatchReceived',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256', name: '', type: 'uint256' },
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256',
            },
            { internalType: 'bytes', name: '', type: 'bytes' },
          ],
          name: 'onERC1155Received',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256', name: '', type: 'uint256' },
            {
              internalType: 'bytes',
              name: '',
              type: 'bytes',
            },
          ],
          name: 'onERC721Received',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
  },
  bsc: {
    FactoryErc721: {
      address: '0xE7C3E5f36c3fCd1DC34fEAD4D09072B48DcF0236',
      abi: [
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          stateMutability: 'nonpayable',
          type: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'newToken',
              type: 'address',
            },
            { indexed: false, internalType: 'string', name: 'name', type: 'string' },
            {
              indexed: false,
              internalType: 'string',
              name: 'symbol',
              type: 'string',
            },
            { indexed: true, internalType: 'address', name: 'signer', type: 'address' },
          ],
          name: 'ERC721Made',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'exchange',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'string', name: 'name', type: 'string' },
            {
              internalType: 'string',
              name: 'symbol',
              type: 'string',
            },
            { internalType: 'string', name: 'baseURI', type: 'string' },
            {
              internalType: 'address',
              name: 'signer',
              type: 'address',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeERC721',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          name: 'setExchange',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
    FactoryErc1155: {
      address: '0x46d41844553A34C30B181346E65324d803723CFf',
      abi: [
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          stateMutability: 'nonpayable',
          type: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'newToken',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'signer', type: 'address' },
          ],
          name: 'ERC1155Made',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'exchange',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'string', name: 'uri', type: 'string' },
            {
              internalType: 'address',
              name: 'signer',
              type: 'address',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeERC1155',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          name: 'setExchange',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
    Exchange: {
      address: '0x0CA49462Cf78dD4b414C1ef60d938BE3cf3150bB',
      abi: [
        { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'seller',
              type: 'address',
            },
            { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
            {
              indexed: false,
              internalType: 'address',
              name: 'sellTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'sellId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'sellAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address',
              name: 'buyTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'buyId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'buyAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address[]',
              name: 'feeAddresses',
              type: 'address[]',
            },
            { indexed: false, internalType: 'uint256[]', name: 'feeAmounts', type: 'uint256[]' },
          ],
          name: 'ExchangeMadeErc1155',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'seller',
              type: 'address',
            },
            { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
            {
              indexed: false,
              internalType: 'address',
              name: 'sellTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'sellId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'sellAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address',
              name: 'buyTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'buyId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'buyAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address[]',
              name: 'feeAddresses',
              type: 'address[]',
            },
            { indexed: false, internalType: 'uint256[]', name: 'feeAmounts', type: 'uint256[]' },
          ],
          name: 'ExchangeMadeErc721',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'idOrder', type: 'bytes32' },
            {
              internalType: 'address[2]',
              name: 'SellerBuyer',
              type: 'address[2]',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToBuy',
              type: 'tuple',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToSell',
              type: 'tuple',
            },
            { internalType: 'address[]', name: 'feeAddresses', type: 'address[]' },
            {
              internalType: 'uint256[]',
              name: 'feeAmounts',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeExchangeERC1155',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'idOrder', type: 'bytes32' },
            {
              internalType: 'address[2]',
              name: 'SellerBuyer',
              type: 'address[2]',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToBuy',
              type: 'tuple',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToSell',
              type: 'tuple',
            },
            { internalType: 'address[]', name: 'feeAddresses', type: 'address[]' },
            {
              internalType: 'uint256[]',
              name: 'feeAmounts',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeExchangeERC721',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256[]', name: '', type: 'uint256[]' },
            {
              internalType: 'uint256[]',
              name: '',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: '', type: 'bytes' },
          ],
          name: 'onERC1155BatchReceived',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256', name: '', type: 'uint256' },
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256',
            },
            { internalType: 'bytes', name: '', type: 'bytes' },
          ],
          name: 'onERC1155Received',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256', name: '', type: 'uint256' },
            {
              internalType: 'bytes',
              name: '',
              type: 'bytes',
            },
          ],
          name: 'onERC721Received',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
  },
  mumbai: {
    FactoryErc721: {
      address: '0xB28A5aEB5ff877095ea607ebaAAd70A7837b048c',
      abi: [
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          stateMutability: 'nonpayable',
          type: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'newToken',
              type: 'address',
            },
            { indexed: false, internalType: 'string', name: 'name', type: 'string' },
            {
              indexed: false,
              internalType: 'string',
              name: 'symbol',
              type: 'string',
            },
            { indexed: true, internalType: 'address', name: 'signer', type: 'address' },
          ],
          name: 'ERC721Made',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'exchange',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'string', name: 'name', type: 'string' },
            {
              internalType: 'string',
              name: 'symbol',
              type: 'string',
            },
            { internalType: 'string', name: 'baseURI', type: 'string' },
            {
              internalType: 'address',
              name: 'signer',
              type: 'address',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeERC721',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          name: 'setExchange',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
    FactoryErc1155: {
      address: '0x17cE9E120Ed491342b9f44c43ecFf3fE1E62a9Ba',
      abi: [
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          stateMutability: 'nonpayable',
          type: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'newToken',
              type: 'address',
            },
            { indexed: true, internalType: 'address', name: 'signer', type: 'address' },
          ],
          name: 'ERC1155Made',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'exchange',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'string', name: 'uri', type: 'string' },
            {
              internalType: 'address',
              name: 'signer',
              type: 'address',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeERC1155',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'address', name: '_exchange', type: 'address' }],
          name: 'setExchange',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
    Exchange: {
      address: '0x3f014A0a1bD5BFaCaf65c0551277E4E82C5Bf0c6',
      abi: [
        { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'seller',
              type: 'address',
            },
            { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
            {
              indexed: false,
              internalType: 'address',
              name: 'sellTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'sellId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'sellAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address',
              name: 'buyTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'buyId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'buyAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address[]',
              name: 'feeAddresses',
              type: 'address[]',
            },
            { indexed: false, internalType: 'uint256[]', name: 'feeAmounts', type: 'uint256[]' },
          ],
          name: 'ExchangeMadeErc1155',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'address',
              name: 'seller',
              type: 'address',
            },
            { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
            {
              indexed: false,
              internalType: 'address',
              name: 'sellTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'sellId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'sellAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address',
              name: 'buyTokenAddress',
              type: 'address',
            },
            { indexed: false, internalType: 'uint256', name: 'buyId', type: 'uint256' },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'buyAmount',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'address[]',
              name: 'feeAddresses',
              type: 'address[]',
            },
            { indexed: false, internalType: 'uint256[]', name: 'feeAmounts', type: 'uint256[]' },
          ],
          name: 'ExchangeMadeErc721',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'previousAdminRole',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
          ],
          name: 'RoleAdminChanged',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleGranted',
          type: 'event',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            { indexed: true, internalType: 'address', name: 'account', type: 'address' },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleRevoked',
          type: 'event',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [],
          name: 'SIGNER_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
        {
          inputs: [
            {
              internalType: 'bytes32',
              name: 'idOrder',
              type: 'bytes32',
            },
            {
              internalType: 'address[2]',
              name: 'SellerBuyer',
              type: 'address[2]',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToBuy',
              type: 'tuple',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToSell',
              type: 'tuple',
            },
            { internalType: 'address[]', name: 'feeAddresses', type: 'address[]' },
            {
              internalType: 'uint256[]',
              name: 'feeAmounts',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeExchangeERC1155',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            {
              internalType: 'bytes32',
              name: 'idOrder',
              type: 'bytes32',
            },
            {
              internalType: 'address[2]',
              name: 'SellerBuyer',
              type: 'address[2]',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToBuy',
              type: 'tuple',
            },
            {
              components: [
                {
                  internalType: 'address',
                  name: 'tokenAddress',
                  type: 'address',
                },
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'amount',
                  type: 'uint256',
                },
              ],
              internalType: 'struct Exchange.NftTokenInfo',
              name: 'tokenToSell',
              type: 'tuple',
            },
            { internalType: 'address[]', name: 'feeAddresses', type: 'address[]' },
            {
              internalType: 'uint256[]',
              name: 'feeAmounts',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: 'signature', type: 'bytes' },
          ],
          name: 'makeExchangeERC721',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256[]', name: '', type: 'uint256[]' },
            {
              internalType: 'uint256[]',
              name: '',
              type: 'uint256[]',
            },
            { internalType: 'bytes', name: '', type: 'bytes' },
          ],
          name: 'onERC1155BatchReceived',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256', name: '', type: 'uint256' },
            {
              internalType: 'uint256',
              name: '',
              type: 'uint256',
            },
            { internalType: 'bytes', name: '', type: 'bytes' },
          ],
          name: 'onERC1155Received',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'address', name: '', type: 'address' },
            {
              internalType: 'address',
              name: '',
              type: 'address',
            },
            { internalType: 'uint256', name: '', type: 'uint256' },
            {
              internalType: 'bytes',
              name: '',
              type: 'bytes',
            },
          ],
          name: 'onERC721Received',
          outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
          stateMutability: 'pure',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            {
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
        },
        {
          inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
          name: 'supportsInterface',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
        },
      ],
    },
  },
};
